# Very simple workflow to deploy the *latest* published container image with the 'latest' tag. 
# This does not post updated module descriptors to okapi, update permissions or enable 
# new versions of a module with the tenant.  If that is needed,  it should be done manually
# via the Okapi API. 

# K8S_NAMESPACE: string; The Kubernetes namespace.
#  'harvester-dev'
# K8S_DEPLOYMENT: string: The module version to deploy.
#  'mod-harvester-admin-0-1-0-snapshot'

name: k8s-deploy-latest

env:
  K8S_NAMESPACE: -- replace: see notes above --
  K8S_DEPLOYMENT: -- replace: see notes above --

on:
  workflow_dispatch

jobs: 
  k8s-deploy-latest:

    runs-on: ubuntu-latest
    steps: 
      - name: Deploy latest to K8s
        uses: actions-hub/kubectl@v1.21.2
        env: 
          KUBE_CONFIG: ${{ secrets.HARVESTER_DEV_SA_KUBECONFIG }}
        with:
          args:
            -n ${{ env.K8S_NAMESPACE }} rollout restart deployment ${{ env.K8S_DEPLOYMENT }}
        
